baseURL = "https://tusitio.com/"
languageCode = "es"
title = "Mi Blog"
theme = "hugo-theme-cleanwhite"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
